// Curated from DS/Day_01..03_Notes.md and DS/FS_Concept_Notes.md.
// The source library retains the detailed contracts and corrections.
export const lessons = [
  {
    id: 'prefix', title: 'Product except self', lane: 'Coding', days: 'Day 1', minutes: 7, priority: 1,
    summary: 'Build exclusive left and right products without division.',
    rule: 'Write the prefix before multiplying the current element.',
    trap: 'With two zeros, every output is zero. Output space is separate from auxiliary space.',
    points: ['Prefix starts at the identity 1', 'A right-to-left suffix multiplies into the answer', 'Time O(n); auxiliary space O(1), excluding output'],
    diagram: `flowchart LR\n A["Input array"] --> B["Left pass: exclusive prefixes"] --> C["Right pass: multiply suffixes"] --> D["Answer"]`,
    lab: 'prefix', sources: ['Day_01_Notes.md', 'Day_01_Practice.md'], quiz: ['Q1-Q6', 'J007'],
  },
  {
    id: 'complexity', title: 'Complexity & recurrences', lane: 'MCQ', days: 'Days 1, 7', minutes: 8, priority: 2,
    summary: 'Count total work, stack depth, output cost, and the cost inside each call.',
    rule: 'A bound describes a runtime function; O, Ω and Θ are not names for cases.',
    trap: 'Two recursive calls can be linear, polynomial or exponential depending on size reduction and pruning.',
    points: ['Recursion tree: sum work across all levels', 'Master Theorem compares a with b^d for T(n)=aT(n/b)+Θ(n^d)', 'Peak stack is not total calls or cumulative allocation'],
    diagram: `flowchart TD\n A["Write recurrence"] --> B{"Subproblem size n/b?"}\n B -->|Yes| C["Compare a with b^d"]\n B -->|No| D["Sum levels or use another method"]\n C --> E["Time bound"]\n D --> E`,
    sources: ['Day_01_Notes.md', 'FS_Concept_Notes.md'], quiz: ['Q7-Q14', 'Q43-Q48', 'J015-J021'],
  },
  {
    id: 'recursion', title: 'Recursion & call state', lane: 'Coding', days: 'Days 1–2', minutes: 9, priority: 1,
    summary: 'See how each call owns local state and how calls return.',
    rule: 'Every path needs a base case and progress toward it.',
    trap: 'An accumulator does not remove Java stack frames; sibling calls do not share local variables.',
    points: ['Draw calls and returns in order', 'Fibonacci has exponential calls but linear active depth', 'Memoization changes repeated work, not the recurrence definition'],
    diagram: `flowchart TD\n A["Call f(n)"] --> B{"Base case?"}\n B -->|Yes| C["Return value"]\n B -->|No| D["Call smaller state"]\n D --> E["Use returned value"]\n E --> C`,
    lab: 'recursion', sources: ['Day_01_Notes.md', 'Day_02_Notes.md'], quiz: ['Q7-Q14', 'J001-J006'],
  },
  {
    id: 'strings', title: 'Strings, GCD & digit rules', lane: 'Coding', days: 'Days 2–3', minutes: 8, priority: 2,
    summary: 'Follow state changes in string recursion and number predicates.',
    rule: 'Euclid repeats (a,b) → (b,a%b) until the remainder is zero.',
    trap: 'Odd strobogrammatic centres are only 0, 1 or 8; happy numbers need cycle detection.',
    points: ['Java String is immutable; a StringBuilder can mutate', 'Keep centre and outer-layer rules distinct', 'A primality loop must include the square-root boundary'],
    diagram: `flowchart LR\n A["GCD(a,b)"] --> B{"b = 0?"}\n B -->|Yes| C["Return a"]\n B -->|No| D["Set a=b, b=a mod b"]\n D --> B`,
    sources: ['Day_02_Notes.md', 'Day_03_Notes.md'], quiz: ['Q15-Q20', 'Q221-Q250', 'J018-J021', 'J152-J160'],
  },
  {
    id: 'quicksort', title: 'Quicksort partition', lane: 'Coding', days: 'Days 4–5', minutes: 9, priority: 1,
    summary: 'Trace Lomuto’s scan and the final pivot swap.',
    rule: 'Before each scan step, values left of i are smaller than the pivot.',
    trap: 'One partition places the pivot, not the entire array. Equal keys can produce quadratic behaviour.',
    points: ['Strict < comparison for this class variant', 'Final pivot index splits the recursive intervals', 'Average Θ(n log n); worst Θ(n²), with recursive stack cost'],
    diagram: `flowchart LR\n A["Choose last pivot"] --> B["Scan j from low to high-1"] --> C{"a[j] < pivot?"}\n C -->|Yes| D["Swap a[i], a[j]; i++"]\n C -->|No| E["Keep scanning"]\n D --> E\n E --> F["Swap pivot into i"]`,
    lab: 'quicksort', sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q21-Q26', 'J008'],
  },
  {
    id: 'majority', title: 'Majority candidate', lane: 'Coding', days: 'Days 4–5', minutes: 6, priority: 2,
    summary: 'Cancel different values, then verify the survivor.',
    rule: 'A majority occurs more than n/2 times.',
    trap: 'Boyer–Moore’s final counter is a cancellation surplus, not the frequency.',
    points: ['Set a candidate when count reaches zero', 'Equal value increments; different value decrements', 'If existence is not promised, count the candidate again'],
    diagram: `flowchart LR\n A["Read value"] --> B{"Count = 0?"}\n B -->|Yes| C["Set candidate"]\n C --> D{"Equals candidate?"}\n B -->|No| D\n D -->|Yes| E["count++"]\n D -->|No| F["count--"]\n E --> G["Verify at end"]\n F --> G`,
    sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q27-Q31', 'J010'],
  },
  {
    id: 'power', title: 'Fast power', lane: 'Coding', days: 'Days 4–5', minutes: 6, priority: 2,
    summary: 'Reuse one half-power result instead of repeating the subtree.',
    rule: 'Compute t=power(x,n/2) once; square t, then multiply x if n is odd.',
    trap: 'Widen INT_MIN before negation; two half calls change time from Θ(log n) to Θ(n).',
    points: ['Base power(x,0)=1', 'Depth Θ(log n)', 'Signed negative exponent needs reciprocal and a wide exponent'],
    diagram: `flowchart TD\n A["power(x,n)"] --> B{"n = 0?"}\n B -->|Yes| C["Return 1"]\n B -->|No| D["t = power(x, floor(n/2)) once"]\n D --> E{"n odd?"}\n E -->|Yes| F["Return t*t*x"]\n E -->|No| G["Return t*t"]`,
    sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q32-Q36', 'J015-J017'],
  },
  {
    id: 'merge', title: 'Merge sort', lane: 'Coding', days: 'Day 6', minutes: 8, priority: 1,
    summary: 'Observe the array just before and during the final merge.',
    rule: 'Merge two sorted halves; choose left on equality to preserve stability.',
    trap: 'The state before the final merge is not the original unsorted array.',
    points: ['Time Θ(n log n) even on sorted input', 'O(n) auxiliary buffer plus O(log n) stack', 'Advance only the pointer whose value was emitted'],
    diagram: `flowchart TD\n A["Split interval"] --> B["Sort left"]\n A --> C["Sort right"]\n B --> D["Merge sorted halves"]\n C --> D\n D --> E["Stable result with left tie"]`,
    lab: 'merge', sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q37-Q42', 'J009'],
  },
  {
    id: 'binary', title: 'Binary search boundaries', lane: 'MCQ', days: 'Days 7–9', minutes: 9, priority: 1,
    summary: 'Watch which half a comparison truly eliminates.',
    rule: 'Choose a closed or half-open interval and preserve it consistently.',
    trap: 'Duplicates change first/last occurrence and rotated-minimum assumptions.',
    points: ['Lower bound is first ≥ target', 'Upper bound is first > target', 'A pruned sorted count can visit only O(log n) boundary nodes'],
    diagram: `flowchart TD\n A["Set search interval"] --> B{"Interval empty?"}\n B -->|Yes| C["Return boundary"]\n B -->|No| D["Test midpoint"]\n D --> E{"Can answer be left?"}\n E -->|Yes| F["Keep left half"]\n E -->|No| G["Keep right half"]\n F --> B\n G --> B`,
    lab: 'binary', sources: ['FS_Concept_Notes.md'], quiz: ['Q49-Q59', 'J022-J028'],
  },
  {
    id: 'koko', title: 'Search on the answer', lane: 'MCQ', days: 'Days 10–11', minutes: 8, priority: 1,
    summary: 'Turn a hard minimum into a monotone yes/no test.',
    rule: 'If speed k is feasible, every greater speed is feasible.',
    trap: 'Each feasibility test scans every pile; the whole method is O(n log maxPile).',
    points: ['Hours = sum ceil(pile/k)', 'Find the first feasible speed', 'Widen before p+k-1 to avoid overflow'],
    diagram: `flowchart LR\n A["Candidate speed k"] --> B["Compute total hours"] --> C{"hours ≤ h?"}\n C -->|Yes| D["Try smaller k"]\n C -->|No| E["Try larger k"]\n D --> F["First feasible speed"]\n E --> F`,
    lab: 'koko', sources: ['FS_Concept_Notes.md'], quiz: ['Q65-Q69', 'J029-J033'],
  },
  {
    id: 'median', title: 'Median partition', lane: 'MCQ', days: 'Days 11–13', minutes: 8, priority: 2,
    summary: 'Partition two sorted arrays so the left side contains half the values.',
    rule: 'Valid cut: leftA ≤ rightB and leftB ≤ rightA.',
    trap: 'Cuts count elements; a zero sentinel is not negative infinity.',
    points: ['Binary search the shorter array', 'Odd total: max(left); even total: mean of boundary values', 'Widen before adding two ints for the mean'],
    diagram: `flowchart TD\n A["Choose cut in shorter array"] --> B["Derive cut in other array"] --> C{"Cross-boundary order valid?"}\n C -->|Yes| D["Read median from four borders"]\n C -->|No| E["Move cut left or right"]\n E --> A`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q70-Q76', 'J034-J038'],
  },
  {
    id: 'lcp', title: 'Longest common prefix', lane: 'MCQ', days: 'Days 10–11', minutes: 5, priority: 2,
    summary: 'Compare one character column across every string.',
    rule: 'Stop at the shortest length or first mismatch.',
    trap: 'Binary searching prefix length still scans characters inside each startsWith test.',
    points: ['Worst case Θ(NL) character checks', 'Empty input needs an explicit policy', 'Java .equals compares text; == compares references'],
    diagram: `flowchart LR\n A["Find shortest length L"] --> B["Check column i in all strings"] --> C{"All equal?"}\n C -->|Yes| D["Advance i"]\n D --> B\n C -->|No| E["Return prefix before i"]`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q60-Q64', 'J039-J042'],
  },
  {
    id: 'greedy', title: 'Greedy choices', lane: 'Coding', days: 'Days 14–18', minutes: 10, priority: 1,
    summary: 'Choose by a proven rule; compare it with a counterexample.',
    rule: 'Fractional knapsack is ordered by value/weight ratio.',
    trap: 'Ratio greedy fails for 0/1 knapsack; coin greedy fails for some denominations.',
    points: ['Fractions make local density choice safe', 'State a proof or exchange argument', 'Stock II sums every positive adjacent gain; Stock I is different'],
    diagram: `flowchart TD\n A["Sort by density"] --> B["Take best remaining item"] --> C{"Fits completely?"}\n C -->|Yes| D["Take all"]\n C -->|No| E["Take fraction and stop"]\n D --> B`,
    lab: 'greedy', sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q77-Q87', 'Q98-Q111', 'J011-J014'],
  },
  {
    id: 'dijkstra', title: 'Graph paths & Dijkstra', lane: 'MCQ', days: 'Days 14–15', minutes: 9, priority: 2,
    summary: 'Finalize the nearest unsettled vertex and relax its edges.',
    rule: 'Dijkstra requires nonnegative edge weights; zero is allowed.',
    trap: 'A matrix that uses zero for “no edge” cannot also represent a zero-weight edge.',
    points: ['Adjacency list versus matrix changes scan cost', 'Relax only when a shorter path is found', 'Heap implementations may hold stale entries'],
    diagram: `flowchart TD\n A["dist[source] = 0"] --> B["Select minimum unsettled vertex"] --> C["Relax outgoing edges"] --> D{"Vertices remain?"}\n D -->|Yes| B\n D -->|No| E["Shortest distances"]`,
    lab: 'dijkstra', sources: ['FS_Concept_Notes.md'], quiz: ['Q88-Q97', 'J043-J049'],
  },
  {
    id: 'mst', title: 'MST, Prim & Kruskal', lane: 'MCQ', days: 'Days 16–18', minutes: 10, priority: 2,
    summary: 'Grow a minimum spanning tree without creating cycles.',
    rule: 'Kruskal accepts the next lightest edge only when its endpoints have different DSU roots.',
    trap: 'E≥V−1 alone does not guarantee a spanning tree; connectivity is required.',
    points: ['DSU path compression speeds repeated finds', 'Rank increments only when equal-rank roots merge', 'Prim grows from a vertex; Kruskal scans sorted edges'],
    diagram: `flowchart LR\n A["Sort edges by weight"] --> B["Find endpoint roots"] --> C{"Same root?"}\n C -->|Yes| D["Reject cycle edge"]\n C -->|No| E["Accept edge; union roots"]\n D --> F["Next edge"]\n E --> F\n F --> B`,
    lab: 'kruskal', sources: ['FS_Concept_Notes.md'], quiz: ['Q112-Q127', 'J050-J065'],
  },
  {
    id: 'bfs', title: 'BFS, DFS & islands', lane: 'MCQ', days: 'Days 19–22', minutes: 10, priority: 2,
    summary: 'See frontier order, visited state, and the difference between queue and stack exploration.',
    rule: 'Mark a node when it enters the BFS queue, preventing duplicate discovery.',
    trap: 'The class maze uses ordinary right/down moves; do not swap in a rolling-ball model.',
    points: ['BFS explores by distance layers in unweighted graphs', 'DFS goes deep then returns', 'Island area counts cells; shape equality needs normalized structure'],
    diagram: `flowchart TD\n A["Start vertex"] --> B["Mark visited and enqueue"] --> C["Dequeue front"] --> D["Scan neighbours"] --> E{"Unvisited?"}\n E -->|Yes| B\n E -->|No| F["Continue scanning"]\n F --> C`,
    lab: 'bfs', sources: ['FS_Concept_Notes.md'], quiz: ['Q128-Q147', 'J066-J081'],
  },
  {
    id: 'trees', title: 'Tree checks & traversals', lane: 'MCQ', days: 'Days 22–24', minutes: 9, priority: 2,
    summary: 'Trace symmetric pairs, heights, levels, and boundary order.',
    rule: 'Balanced-tree checks can return a height or a failure sentinel in one pass.',
    trap: 'Recomputing height at every node may turn an O(n) check into O(n²).',
    points: ['Mirror compares outer and inner child pairs', 'Level averages use the current queue size', 'Boundary traversal avoids double-counting leaves'],
    diagram: `flowchart TD\n A["Check subtree"] --> B["Get left height or fail"]\n A --> C["Get right height or fail"]\n B --> D{"Difference ≤ 1?"}\n C --> D\n D -->|Yes| E["Return 1 + max height"]\n D -->|No| F["Return failure sentinel"]`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q133-Q135', 'Q148-Q165', 'J082-J100'],
  },
  {
    id: 'backtracking', title: 'Backtracking & N-Queens', lane: 'MCQ', days: 'Days 25–27', minutes: 10, priority: 2,
    summary: 'Place, recurse, and undo a choice before trying the next one.',
    rule: 'The undo step must restore all shared state.',
    trap: 'A Hamiltonian path is not a cycle until the closing edge exists.',
    points: ['N-Queens checks columns and diagonals', 'Gold search restores a cell after each path', 'Campus Bikes minimizes total distance, not each local distance'],
    diagram: `flowchart TD\n A["Choose candidate"] --> B{"Safe?"}\n B -->|No| C["Try next"]\n B -->|Yes| D["Place and recurse"]\n D --> E["Undo placement"]\n E --> C\n C --> A`,
    lab: 'queens', sources: ['FS_Concept_Notes.md'], quiz: ['Q166-Q180', 'Q191-Q195', 'J101-J115', 'J126-J130'],
  },
  {
    id: 'generators', title: 'Brace expansion & Gray code', lane: 'MCQ', days: 'Days 26–27', minutes: 8, priority: 3,
    summary: 'Track choices in string grammar and one-bit state changes.',
    rule: 'Brace comma means union; adjacency means Cartesian concatenation.',
    trap: 'Gray code XOR toggles a bit; OR does not. Nested braces need nesting-aware parsing.',
    points: ['Gray(i)=i^(i>>1) constructs a reflected sequence', 'Generalized abbreviations flush pending counts', 'Output size can dominate running time'],
    diagram: `flowchart TD\n A["Parse expression"] --> B{"Top-level comma?"}\n B -->|Yes| C["Union alternatives"]\n B -->|No| D["Concatenate adjacent groups"]\n C --> E["Deduplicate and sort"]\n D --> E`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q181-Q200', 'J116-J125', 'J131-J135'],
  },
  {
    id: 'language', title: 'Java MCQ traps & C++ coding I/O', lane: 'Exam', days: 'Exam platform', minutes: 10, priority: 1,
    summary: 'Separate Java expression rules from C++ implementation and input handling.',
    rule: 'Read the exact print point; short-circuiting and early returns change which lines execute.',
    trap: 'Java overflow wraps; C++ signed overflow is undefined. Java operands evaluate left to right.',
    points: ['MCQ snippets are Java-only', 'Coding references include C++17 and Java', 'Practice full main, parser, and output loop before timed coding'],
    diagram: `flowchart LR\n A["Read exam task"] --> B{"MCQ or coding?"}\n B -->|MCQ| C["Apply Java semantics"]\n B -->|Coding| D["Choose language and I/O contract"]\n C --> E["Trace exact state"]\n D --> F["Implement and test edges"]`,
    sources: ['FS_Java_CPP_Exam_Revision.md', 'FS_Java_Validation.md'], quiz: ['J136-J151'],
  },
]

lessons.push(
  {
    id: 'fixedpoint', title: 'Fixed points & common rows', lane: 'MCQ', days: 'Day 9', minutes: 7, priority: 3,
    summary: 'Test whether a sorted property is actually monotone before searching it.',
    rule: 'For distinct increasing integers, g(i)=a[i]-i is nondecreasing.',
    trap: 'Duplicates break that proof; repeated values in one matrix row count only once for row membership.',
    points: ['Find the first g≥0, then test equality', 'Search each sorted row for candidates from row 0', 'Rows sorted separately do not imply flattened order'],
    diagram: `flowchart TD\n A["Check sorted input"] --> B{"Values distinct?"}\n B -->|Yes| C["Binary search first a[i]-i >= 0"]\n B -->|No| D["Monotonic proof fails"]\n C --> E["Test a[i] = i"]`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q55-Q59', 'J027-J028'],
  },
  {
    id: 'stock', title: 'Stock I vs Stock II', lane: 'Coding', days: 'Days 15–16', minutes: 6, priority: 2,
    summary: 'Compare one transaction with unlimited transactions.',
    rule: 'One trade tracks the earliest minimum; unlimited trades sum positive adjacent rises.',
    trap: 'A fee, cooldown or holding rule changes the formula.',
    points: ['[7,1,5,3,6,4] gives 5 for one trade', 'The same prices give 7 for unlimited trades', 'Both simple variants take Θ(n) time and O(1) space'],
    diagram: `flowchart TD\n A["Read stock contract"] --> B{"One transaction?"}\n B -->|Yes| C["Track min price and best later gain"]\n B -->|No| D["Sum every positive adjacent increase"]\n C --> E["Return max profit"]\n D --> E`,
    sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q98-Q102', 'J011'],
  },
  {
    id: 'minproduct', title: 'Minimum subset product', lane: 'Coding', days: 'Days 16–17', minutes: 7, priority: 2,
    summary: 'Choose a nonempty subset whose product is as small as possible.',
    rule: 'An odd number of negative factors gives a negative product; an even count may require dropping the closest-to-zero negative.',
    trap: 'This is an arbitrary subset of integers, not the maximum contiguous-subarray problem.',
    points: ['Handle all-zero and singleton cases explicitly', 'Avoid zero when a negative product exists', 'Widen intermediate multiplication before overflow'],
    diagram: `flowchart TD\n A["Count negatives and zeros"] --> B{"Odd negative count?"}\n B -->|Yes| C["Use all nonzero factors"]\n B -->|No| D{"Positive even negative count?"}\n D -->|Yes| E["Drop smallest-absolute negative"]\n D -->|No| F["Choose zero or smallest positive"]`,
    sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q103-Q107', 'J013'],
  },
  {
    id: 'maxswap', title: 'Maximum Swap', lane: 'Coding', days: 'Day 18', minutes: 6, priority: 2,
    summary: 'Improve the earliest digit with at most one swap.',
    rule: 'For each position, know the rightmost maximum digit in its suffix.',
    trap: 'For 1993, swap with the second 9 to get 9913; sorting every digit solves a different task.',
    points: ['Build suffix-max indices right to left', 'At first improvable position, swap and stop', 'Θ(d) time; O(d) suffix storage'],
    diagram: `flowchart LR\n A["Build rightmost suffix maxima"] --> B["Scan positions left to right"] --> C{"Larger digit to right?"}\n C -->|Yes| D["Swap once and stop"]\n C -->|No| E["Advance"]\n E --> C`,
    sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q108-Q111', 'J014'],
  },
  {
    id: 'coins', title: 'Coin greedy counterexample', lane: 'Coding', days: 'Day 14', minutes: 6, priority: 2,
    summary: 'See why the biggest affordable coin is not always the best move.',
    rule: 'Coin greedy needs a proof for the denomination system.',
    trap: 'With {1,3,4,5} and amount 7, greedy uses three coins; 3+4 uses two.',
    points: ['Count coins, not combinations or ordered sequences', 'A missing 1 can make leftover unreachable', 'Activity selection is a different greedy proof'],
    diagram: `flowchart TD\n A["Amount 7, coins 1 3 4 5"] --> B["Greedy: take 5"]\n B --> C["Take 1 and 1: 3 coins"]\n A --> D["Alternative: 3 and 4"]\n D --> E["2 coins, so greedy fails"]`,
    lab: 'coins', sources: ['FS_Concept_Notes.md', 'FS_Coding_Gap_Practice.md'], quiz: ['Q83-Q87'],
  },
  {
    id: 'islands', title: 'Island count, area & shape', lane: 'MCQ', days: 'Days 19–20', minutes: 8, priority: 2,
    summary: 'Flood each four-direction component once, then ask which property the question wants.',
    rule: 'Count starts for number of islands; count cells for area; normalize offsets for shape.',
    trap: 'Equal area does not imply equal shape. Diagonal contact is separate under four-direction adjacency.',
    points: ['Mark visited before revisiting land', 'A shape key can sort relative coordinates', 'Destructive marking changes later calls unless reset'],
    diagram: `flowchart TD\n A["Scan grid"] --> B{"Unvisited land?"}\n B -->|Yes| C["Flood four directions"]\n C --> D["Count cells and normalize offsets"]\n D --> E["Update count, max area, shape set"]\n B -->|No| F["Next cell"]\n E --> F`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q136-Q141', 'J076-J081'],
  },
  {
    id: 'boundary', title: 'Tree boundary', lane: 'MCQ', days: 'Day 22', minutes: 7, priority: 2,
    summary: 'Walk the anti-clockwise outer edge without duplicate leaves.',
    rule: 'Root once, left edge top-down, leaves left-to-right, right edge bottom-up.',
    trap: 'Boundary sides exclude leaves; a one-node tree outputs the root once.',
    points: ['Left edge falls back to right child if needed', 'Right edge falls back to left child', 'Time Θ(n), plus output and traversal stack'],
    diagram: `flowchart LR\n A["Root once"] --> B["Left boundary, no leaves"] --> C["All leaves left to right"] --> D["Right boundary reversed, no leaves"]`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q148-Q151', 'J097-J100'],
  },
  {
    id: 'gold', title: 'Maximum gold path', lane: 'MCQ', days: 'Day 25', minutes: 7, priority: 3,
    summary: 'Try every start and follow simple paths through positive cells.',
    rule: 'A cell is blocked only for the current path; restore it after recursion.',
    trap: 'A connected component sum may be impossible as one path when branches require revisiting a hub.',
    points: ['Move in four directions', 'Accumulate path sum and keep global maximum', 'A permanent visited set across starts loses valid paths'],
    diagram: `flowchart TD\n A["Choose positive start"] --> B["Mark current cell unavailable"] --> C["Try four neighbours"]\n C --> D["Update best path sum"]\n D --> E["Restore cell"]\n E --> F["Try next start"]`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q172-Q175', 'J107-J110'],
  },
  {
    id: 'hamiltonian', title: 'Hamiltonian cycle', lane: 'MCQ', days: 'Day 26', minutes: 7, priority: 3,
    summary: 'Visit every vertex once, then check the closing edge.',
    rule: 'A full path is a cycle only if its last vertex connects to its first.',
    trap: 'Hamiltonian uses vertices; Eulerian uses edges. Finding any cycle does not minimize tour weight.',
    points: ['Reject used vertices and absent next edges', 'Fixing start removes rotational duplicates', 'Worst-case search is exponential or factorial'],
    diagram: `flowchart TD\n A["Fix start vertex"] --> B["Add unused adjacent vertex"] --> C{"All vertices used?"}\n C -->|No| B\n C -->|Yes| D{"Closing edge exists?"}\n D -->|Yes| E["Hamiltonian cycle"]\n D -->|No| F["Backtrack"]\n F --> B`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q176-Q180', 'J111-J115'],
  },
  {
    id: 'campus', title: 'Campus Bikes assignment', lane: 'MCQ', days: 'Day 27', minutes: 8, priority: 3,
    summary: 'Assign distinct bikes to workers while minimizing total Manhattan distance.',
    rule: 'Try every unused bike for the next worker, recurse, then unmark it.',
    trap: 'Nearest bike for the current worker need not minimize total cost.',
    points: ['Distance is |dx|+|dy|', 'Track accumulated total across all workers', 'Memoizing worker index and used-bike mask is a small-M extension'],
    diagram: `flowchart TD\n A["Next worker"] --> B["Try each unused bike"] --> C["Add Manhattan distance"]\n C --> D["Recurse"]\n D --> E["Unmark bike"]\n E --> F["Keep minimum total"]`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q191-Q195', 'J126-J130'],
  },
  {
    id: 'gray', title: 'Gray code & bit flips', lane: 'MCQ', days: 'Day 27', minutes: 6, priority: 3,
    summary: 'Walk states where consecutive values differ in exactly one bit.',
    rule: 'XOR toggles a bit; reflected Gray order can be generated by i^(i>>1).',
    trap: 'OR may leave an already-set bit unchanged. A local greedy walk is not a general proof of a complete cycle.',
    points: ['An n-bit sequence has 2^n distinct states', 'Cyclic variants also test last-to-first', 'Materializing the output costs Θ(2^n) words'],
    diagram: `flowchart LR\n A["Binary index i"] --> B["Shift right once"] --> C["XOR with i"] --> D["Gray value"]\n D --> E["Adjacent values differ in one bit"]`,
    sources: ['FS_Concept_Notes.md'], quiz: ['Q186-Q190', 'J121-J125'],
  },
)

export const lessonById = Object.fromEntries(lessons.map((lesson) => [lesson.id, lesson]))
