(() => {
  'use strict';
  const {subjects, lessons, questions, glossary, sources, diagrams, official, aiLabel} = JSON.parse(document.getElementById('atlas-data').textContent);
  const lessonById = Object.fromEntries(lessons.map(x => [x.id,x]));
  const questionById = Object.fromEntries(questions.map(x => [x.id,x]));
  const sourceById = Object.fromEntries(sources.map(x => [x.id,x]));
  const root = document.getElementById('app');
  const storageKey = 'fs-subject-atlas-v1';
  function readState(){try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return {}}}
  let saved=readState();
  saved={studied:[],history:{},theme:'light',quiz:null,...saved};
  if(!Array.isArray(saved.studied))saved.studied=[];
  if(!saved.history||typeof saved.history!=='object')saved.history={};
  let lessonTab='visual',traceStep=0,activeLesson='',mobileOpen=false,diagramToken=0;
  let filters={search:'',subject:'all',basis:'all',status:'all'};
  let lab={gitStep:0,network:'GBN',lost:1,w1:0.5,w2:-1,bias:1,clicks:0};
  const diagramCache=new Map();
  const htmlCache=new Map();
  function store(){try{localStorage.setItem(storageKey,JSON.stringify(saved))}catch{}}
  function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function route(){const raw=(location.hash||'#/home').slice(2);const [path,query='']=raw.split('?');const [page,id]=path.split('/');return {page:['home','learn','practice','sources','terms','coverage'].includes(page)?page:'home',id:id?decodeURIComponent(id):'',params:new URLSearchParams(query)}}
  function go(path){if(location.hash===`#/${path}`)render();else location.hash=`#/${path}`;mobileOpen=false;window.scrollTo(0,0)}
  const link=(path,label,cls='')=>`<a class="${cls}" href="#/${path}">${label}</a>`;
  const badge=()=>`<span class="ai-badge">${esc(aiLabel)}</span>`;
  function basisText(l){return l.basis==='gap'?'Supplement required':l.basis==='partial'?'Partial college coverage':'College topic available'}
  function provenance(l){
    const note=l.basis==='gap'?'A focused college explanation was not found for this topic. This lesson supplies the missing coverage.':l.basis==='partial'?'The files contain an introduction or a small example. This lesson adds the missing rules and worked steps.':'The linked college notes cover this topic. The explanations, diagrams and revision questions are newly authored study aids.';
    return `<div class="provenance">${badge()} <span class="source-badge">${basisText(l)}</span><p>${esc(note)} The label identifies new AI teaching content; the source status states whether the underlying topic is in your files.</p></div>`;
  }
  function sourceLinks(l){return `<div class="source-links">${l.sources.map(id=>sourceById[id]?link(`sources/${id}`,esc(sourceById[id].name)):'').join('')}${l.refs.map(id=>official[id]?`<a href="${esc(official[id][1])}" target="_blank" rel="noopener noreferrer">${esc(official[id][0])} ↗</a>`:'').join('')||'<p>No focused college source was located. See the linked official references.</p>'}</div>`}
  function footer(){return `<p class="footer-note">Revision scope: the announced FS topics for SE, WT, CN and AI. Practice questions are newly written; they do not predict the test. Original source files retain their wording. Explanations use short, direct sentences inspired by ASD-STE100, without claiming full controlled-dictionary compliance.</p>`}
  function render(){
    const r=route();document.body.classList.toggle('dark',saved.theme==='dark');
    const names={home:'Overview',learn:'Learn visually',practice:'MCQ practice',sources:'Source library',terms:'Terms in plain words',coverage:'Coverage & provenance'};
    root.innerHTML=`<button class="mobile-overlay ${mobileOpen?'open':''}" data-action="menu" aria-label="Close navigation"></button><aside class="sidebar ${mobileOpen?'open':''}"><a class="brand" href="#/home"><span class="brand-icon">✳</span><span>Subject Atlas<small>SE · WT · CN · AI</small></span></a><nav class="nav" aria-label="Main navigation">${[['home','⌂','Overview'],['learn','◇','Learn visually'],['practice','✓','MCQ practice'],['sources','▤','Source library'],['terms','Aa','Terms in plain words'],['coverage','◎','Coverage & provenance']].map(([p,i,n])=>link(p,`<b aria-hidden="true">${i}</b>${n}`,r.page===p?'active':'')).join('')}</nav><span class="kicker">Your subjects</span><div class="side-subjects">${Object.entries(subjects).map(([k,v])=>`<a href="#/learn?subject=${k}"><span class="dot" style="--accent:${v.color}"></span>${k} · ${v.name}</a>`).join('')}</div><div class="side-bottom"><span class="kicker">Revision progress</span><div class="side-progress"><span style="width:${saved.studied.length/lessons.length*100}%"></span></div><span>${saved.studied.length} / ${lessons.length} lessons marked studied</span><p>Screening · 9 October 2026</p><a href="http://127.0.0.1:5173/" target="_blank" rel="noopener">Open the separate DAA site ↗</a></div></aside><div class="shell"><header class="topbar"><button class="btn mobile-menu" data-action="menu" aria-label="Open navigation">☰</button><span class="crumb">FS / ${names[r.page]}${r.id&&lessonById[r.id]?` / ${lessonById[r.id].subject}`:''}</span><span class="exam">SE · WT · CN · AI</span><button class="btn" data-action="theme" aria-label="Switch color theme">${saved.theme==='dark'?'☀ Light':'◐ Dark'}</button></header><main class="page" id="main">${pageHtml(r)}</main></div>`;
    document.title=`${r.page==='learn'&&lessonById[r.id]?lessonById[r.id].title:names[r.page]} · Subject Atlas`;
    bindPage(r);
  }
  function pageHtml(r){
    if(r.page==='home')return home();
    if(r.page==='learn')return r.id?lessonPage(r.id):learnIndex(r);
    if(r.page==='practice')return saved.quiz?.open?quizPage():practiceModes();
    if(r.page==='sources')return sourcesPage(r.id);
    if(r.page==='terms')return termsPage();
    return coveragePage();
  }
  function statsFor(subject){const pool=questions.filter(q=>!subject||q.subject===subject);const done=pool.filter(q=>saved.history[q.id]);return {count:pool.length,done:done.length,correct:done.filter(q=>saved.history[q.id].correct).length}}
  function home(){const st=statsFor();return `<section class="hero"><div class="hero-copy"><span class="kicker">Four subjects · one clear study route</span><h1>See the process.<br>Explain the next step.</h1><p>Work through concrete examples, inspect the diagrams, and test your understanding. Start with a subject, then use its visual lessons and MCQs.</p><div class="hero-actions">${link('learn','Explore visual lessons →','btn primary')}${link('practice','Start MCQ practice','btn')}</div></div><div class="hero-art" aria-label="The four subjects">${Object.entries(subjects).map(([s,v])=>`<div class="orbit-row" style="--accent:${v.color}"><b>${s}</b><span>${v.name}</span><em>→</em></div>`).join('')}</div></section><div class="stats"><div class="stat"><strong>${lessons.length}</strong><span>Visual lessons</span></div><div class="stat"><strong>${questions.length}</strong><span>Original revision MCQs</span></div><div class="stat"><strong>${saved.studied.length}</strong><span>Lessons marked studied</span></div><div class="stat"><strong>${st.done?Math.round(st.correct/st.done*100)+'%':'—'}</strong><span>Correct on latest checked answers · ${st.done} questions</span></div></div><div class="section-title"><h2>Choose a subject</h2>${link('coverage','Check material coverage →')}</div><section class="subject-grid">${Object.entries(subjects).map(([s,v])=>{const ls=lessons.filter(l=>l.subject===s),st=statsFor(s);return `<article class="panel subject-card" style="--accent:${v.color}"><div class="subject-head"><span class="pill">${s}</span><span class="subject-icon" aria-hidden="true">${v.icon}</span></div><h2>${v.name}</h2><p>${v.brief}</p><div class="subject-meta"><span><b>${ls.length}</b>lessons</span><span><b>${st.count}</b>questions</span><span><b>${ls.filter(l=>saved.studied.includes(l.id)).length}</b>studied</span></div><div class="actions">${link(`learn?subject=${s}`,'Learn visually','btn primary')}<button class="btn" data-action="start-subject" data-subject="${s}">Practise MCQs</button></div></article>`}).join('')}</section><div class="section-title"><h2>A useful order for each lesson</h2></div><div class="panel"><div class="trace-path">${['1 · Read the starting state','2 · Step through the example','3 · Explain why the result follows','4 · Check with MCQs'].map(x=>`<div class="notice positive">${x}</div>`).join('')}</div><p class="muted">A studied mark records your revision activity. It does not certify mastery. Check the source status and assumptions when a rule depends on a particular model.</p></div>${footer()}`}
  function learnIndex(r){const subject=r.params.get('subject');if(subject&&subjects[subject])filters.subject=subject;return `<div class="page-intro"><span class="kicker">Learn visually</span><h1>Follow a state change.</h1><p>Each lesson connects a rule to a fixed example. Use the walkthrough, the interactive Archify diagram, and the comparison table.</p></div><div class="filters"><label>Search topic or explanation<input id="lesson-search" type="search" value="${esc(filters.search)}" placeholder="Promises, Git, framing, neuron…"></label><label>Subject<select id="lesson-subject"><option value="all">All four subjects</option>${Object.keys(subjects).map(s=>`<option ${filters.subject===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Source coverage<select id="lesson-basis"><option value="all">All coverage</option>${[['college','College topic available'],['partial','Partial college coverage'],['gap','Supplement required']].map(([v,n])=>`<option value="${v}" ${filters.basis===v?'selected':''}>${n}</option>`).join('')}</select></label><label>Revision status<select id="lesson-status"><option value="all">All lessons</option><option value="new" ${filters.status==='new'?'selected':''}>Not marked studied</option><option value="studied" ${filters.status==='studied'?'selected':''}>Marked studied</option></select></label></div><div id="lesson-results">${lessonCards()}</div>${footer()}`}
  function lessonCards(){const needle=filters.search.toLowerCase();const pool=lessons.filter(l=>(filters.subject==='all'||l.subject===filters.subject)&&(filters.basis==='all'||l.basis===filters.basis)&&(filters.status==='all'||saved.studied.includes(l.id)===(filters.status==='studied'))&&`${l.title} ${l.summary} ${l.explain.join(' ')}`.toLowerCase().includes(needle));return `<p class="result-count">${pool.length} of ${lessons.length} lessons · Each diagram is a worked teaching path, not a complete model of every possible case.</p><div class="lesson-grid">${pool.map(l=>`<a href="#/learn/${l.id}" class="lesson-card" style="--accent:${subjects[l.subject].color}"><div class="card-labels"><span class="pill">${l.subject}</span><span class="source-badge">${basisText(l)}</span></div><h2>${esc(l.title)}</h2><p>${esc(l.summary)}</p><footer><span>${saved.studied.includes(l.id)?'✓ Marked studied':'4 worked steps · 4 MCQs'}</span><b>Open lesson →</b></footer></a>`).join('')||'<div class="empty">No lessons match these filters.</div>'}</div>`}
  function lessonPage(id){const l=lessonById[id];if(!l)return `<div class="empty">This lesson does not exist. ${link('learn','Return to the lesson list')}</div>`;if(activeLesson!==id){activeLesson=id;traceStep=0;lessonTab='visual'}return `${link(`learn?subject=${l.subject}`,'← All '+l.subject+' lessons','back')}<div class="lesson-heading"><div><span class="pill">${l.subject}</span><h1>${esc(l.title)}</h1><p>${esc(l.summary)}</p></div><button class="btn ${saved.studied.includes(id)?'selected':'primary'}" data-action="studied" data-id="${id}">${saved.studied.includes(id)?'✓ Marked studied':'Mark studied'}</button></div>${provenance(l)}<div class="tabs" role="tablist" aria-label="Lesson views">${[['visual','Diagram & walkthrough'],['read','Read the lesson'],['compare','Compare & check']].map(([t,n])=>`<button role="tab" id="tab-${t}" aria-controls="lesson-content" aria-selected="${lessonTab===t}" tabindex="${lessonTab===t?'0':'-1'}" data-action="tab" data-tab="${t}">${n}</button>`).join('')}</div><section id="lesson-content" role="tabpanel" aria-labelledby="tab-${lessonTab}">${lessonTab==='visual'?visualPage(l):lessonTab==='read'?readingPage(l):comparePage(l)}</section>${footer()}`}
  function aside(l){return `<aside class="lesson-aside"><section class="panel limit-panel"><span class="kicker">A limit to remember</span><p>${esc(l.trap)}</p></section><section class="panel"><span class="kicker">Where this comes from</span>${sourceLinks(l)}</section><section class="panel"><span class="kicker">Check your understanding</span><p>Four questions for this lesson. Read the reason after checking each answer.</p><button class="btn primary" data-action="start-lesson" data-id="${l.id}">Practise this lesson</button></section></aside>`}
  function readingPage(l){return `<div class="reading-layout"><article class="panel"><span class="kicker">Build the idea</span><h2>${esc(l.title)}</h2>${l.explain.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="why"><h3>Why the result follows</h3><p>${esc(l.why)}</p></div><h3>Use a concrete example</h3><pre>${esc(l.example)}</pre><span class="kicker">Expected result</span><div class="output">${esc(l.output)}</div><p>Use ${link('terms','the glossary')} when a term needs clarification.</p></article>${aside(l)}</div>`}
  function comparePage(l){return `<div class="reading-layout"><article class="panel"><span class="kicker">Keep the distinctions clear</span><h2>Compare the roles</h2><table class="comparison"><tbody>${l.compare.map(([a,b])=>`<tr><th scope="row">${esc(a)}</th><td>${esc(b)}</td></tr>`).join('')}</tbody></table><div class="why"><h3>Check the assumption</h3><p>${esc(l.trap)}</p></div><h3>Explain these before selecting an answer</h3><div class="question-links">${questions.filter(q=>q.lesson===l.id).map(q=>`<button class="btn" data-action="start-question" data-id="${q.id}">${esc(q.prompt.split('\n')[0])} →</button>`).join('')}</div></article>${aside(l)}</div>`}
  function visualPage(l){return `<div class="visual-grid"><section class="trace-panel"><span class="kicker">A controlled example</span><h2>See what changes.</h2><p class="muted">Use the numbered steps. The state and its reason change together.</p><div id="trace">${traceHtml(l)}</div></section><section class="panel lab-panel"><span class="kicker">Change an input</span><h2>${l.subject==='SE'?'Git snapshot explorer':l.subject==='WT'?'A real DOM event':l.subject==='CN'?'ARQ comparison':'Neuron calculator'}</h2><div id="lab">${labHtml(l.subject)}</div><p>This subject explorer is a separate fixed model. It does not replace the lesson’s full topic or claim to execute external tools.</p></section></div><section class="panel"><div class="diagram-intro"><div><span class="kicker">Interactive Archify diagram</span><h2>Inspect the path.</h2><p>Use the diagram’s zoom, search, focus and relationship tools. Click a node to inspect it. Open the full viewer for a wider canvas and exports.</p></div><button class="btn" data-action="open-diagram" data-id="${l.id}">Open full diagram ↗</button></div><p class="diagram-loading" id="diagram-status" role="status">Opening the local diagram…</p><iframe id="diagram" class="diagram-frame" title="Interactive diagram: ${esc(l.title)}" sandbox="allow-scripts allow-downloads allow-popups" allowfullscreen></iframe><div class="notice"><b>Scope of this picture</b><p>The nodes trace the lesson’s chosen example. Other paths, failure cases, and model variants are described in the lesson and its limits. ${l.sources.length?'The college notes provide the underlying topic.':'This topic fills a material gap.'}</p></div></section><div class="section-title"><h2>Connect the diagram to the rule</h2><button class="btn" data-action="tab" data-tab="read">Read the explanation →</button></div><div class="panel"><p>${esc(l.why)}</p><div class="actions"><button class="btn primary" data-action="start-lesson" data-id="${l.id}">Try the four MCQs</button>${link('terms','Look up a term','btn')}</div></div>`}
  function traceHtml(l){const t=l.trace[traceStep];return `<div class="trace-path">${l.trace.map((s,i)=>`<button data-action="trace-step" data-step="${i}" class="${i===traceStep?'active':''}" aria-pressed="${i===traceStep}"><b>${i+1}</b>${esc(s.title)}</button>`).join('')}</div><div class="trace-state" aria-live="polite"><h3>${esc(t.title)}</h3><strong>${esc(t.state)}</strong><p>${esc(t.reason)}</p></div><div class="trace-controls"><button class="btn" data-action="trace-prev" ${traceStep===0?'disabled':''}>← Previous</button><small>Step ${traceStep+1} of ${l.trace.length}</small><button class="btn primary" data-action="trace-next" ${traceStep===l.trace.length-1?'disabled':''}>Next →</button></div>`}
  function updateTrace(step){const l=lessonById[route().id];if(!l)return;traceStep=Math.max(0,Math.min(l.trace.length-1,step));const el=document.getElementById('trace');if(el)el.innerHTML=traceHtml(l)}
  function labHtml(subject){
    if(subject==='SE'){const states=[['original','—','original'],['A','—','original'],['A','A','original'],['B','A','original'],['B','A','A']][lab.gitStep];return `<p>Stage A, then edit to B. Predict which version the commit records.</p><div class="lab-states">${['Working tree','Staging area','HEAD snapshot'].map((n,i)=>`<div class="lab-state"><span>${n}</span><b>${states[i]}</b></div>`).join('')}</div><div class="actions">${['Reset','Edit A','Stage A','Edit B','Commit'].map((n,i)=>`<button class="btn ${i===lab.gitStep?'selected':''}" data-action="git-step" data-step="${i}">${n}</button>`).join('')}</div><div class="lab-result" style="margin-top:18px">${['Start with a committed original file.','A is an unstaged edit.','The index now selects A.','B is an additional unstaged edit.','The commit records A. The current B edit remains unstaged.'][lab.gitStep]}</div>`}
    if(subject==='WT')return `<p>This button has an actual event listener. The page changes the live node’s text when you click.</p><div class="dom-demo"><span>Visible count: <b id="dom-count">${lab.clicks}</b></span><button class="btn primary" data-action="dom-click">Dispatch a click</button></div><pre>count += 1;\nnode.textContent = String(count);</pre><button class="btn" data-action="dom-reset">Reset count</button><p>The event updates the current page. It does not rewrite the original file on disk.</p>`;
    if(subject==='CN'){const sr=lab.network==='SR';return `<p>Send frames 0–3, lose one frame, and compare the textbook recovery rules.</p><label>Protocol<select id="network-protocol"><option value="GBN" ${!sr?'selected':''}>Go-Back-N</option><option value="SR" ${sr?'selected':''}>Selective Repeat</option></select></label><label>Lost frame<select id="network-lost">${[0,1,2,3].map(i=>`<option value="${i}" ${i===lab.lost?'selected':''}>${i}</option>`).join('')}</select></label><div class="packet-row">${[0,1,2,3].map(i=>`<div class="packet ${i===lab.lost?'lost':i>lab.lost?'buffer':''}" aria-label="Frame ${i}: ${i===lab.lost?'lost':i>lab.lost?sr?'buffered':'discarded':'accepted'}">${i}</div>`).join('')}</div><div class="lab-result">Resend: <strong>${(sr?[lab.lost]:[0,1,2,3].filter(i=>i>=lab.lost)).join(', ')}</strong><p>${sr?'Correct later frames can remain buffered.':'Correct later frames were discarded because a gap prevented in-order acceptance.'}</p></div>`}
    const z=2*lab.w1+3*lab.w2+lab.bias;return `<p>Fixed inputs: x₁ = 2, x₂ = 3. Change the parameters and calculate z, then ReLU(z).</p>${[['w1','Weight 1',lab.w1],['w2','Weight 2',lab.w2],['bias','Bias',lab.bias]].map(([k,n,v])=>`<label><span>${n}</span><input type="range" data-parameter="${k}" min="-2" max="2" step="0.1" value="${v}" aria-label="${n}"><b id="value-${k}">${v.toFixed(1)}</b></label>`).join('')}<div class="lab-result" id="neuron-result">${neuronResult(z)}</div>`;
  }
  function neuronResult(z){return `z = 2(${lab.w1.toFixed(1)}) + 3(${lab.w2.toFixed(1)}) + ${lab.bias.toFixed(1)}<p>Pre-activation: <strong>${z.toFixed(1)}</strong></p><p>ReLU output: <strong>${Math.max(0,z).toFixed(1)}</strong></p>`}
  async function diagramHtml(id){if(htmlCache.has(id))return htmlCache.get(id);const d=diagrams[id];if(!d)throw Error('The local diagram is missing.');if(!('DecompressionStream' in window))throw Error('This browser cannot open compressed diagrams. Use the original local diagram link.');const bytes=Uint8Array.from(atob(d.gzip),c=>c.charCodeAt(0));const text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();htmlCache.set(id,text);return text}
  async function loadDiagram(id){const token=++diagramToken;try{const html=await diagramHtml(id);if(token!==diagramToken||route().id!==id)return;const frame=document.getElementById('diagram');if(frame){frame.srcdoc=html;document.getElementById('diagram-status').textContent='Local diagram ready. Its controls work inside the viewer.'}}catch(e){const el=document.getElementById('diagram-status');if(el)el.innerHTML=`${esc(e.message)} <a href="../diagrams/html/${encodeURIComponent(id)}.html" target="_blank" rel="noopener">Open the original diagram</a>`}}
  async function openDiagram(id){let win=window.open('about:blank','_blank');if(!win)return;win.opener=null;try{const html=await diagramHtml(id);const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));diagramCache.set(id,url);win.location.replace(url)}catch(e){win.close();alert(e.message)}}
  function shuffle(a){const v=[...a];for(let i=v.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[v[i],v[j]]=[v[j],v[i]]}return v}
  function mistakes(){return questions.filter(q=>saved.history[q.id]&&!saved.history[q.id].correct)}
  function practiceModes(){const st=statsFor();return `<div class="page-intro"><span class="kicker">MCQ practice</span><h1>Make a choice. Explain the reason.</h1><p>${questions.length} original questions across the four subjects. Practice gives immediate explanations. The timed mock reveals answers when you submit.</p></div>${saved.quiz?`<div class="notice positive"><b>A saved session is available.</b><p>${esc(saved.quiz.title)} · ${Object.keys(saved.quiz.responses).length} answers selected. <button class="btn" data-action="resume">Resume session</button></p></div>`:''}<p class="result-count">${st.done} unique questions checked · ${mistakes().length} incorrect on the latest checked attempt.</p><div class="mode-grid"><button class="mode-card feature" data-action="start-mixed"><span class="pill">30 questions · 30 minutes</span><h2>Mixed screening practice</h2><p>8 SE, 8 WT, 7 CN and 7 AI questions, shuffled. This balance is a practice choice, not the announced marks distribution.</p><strong>Start timed mock →</strong></button><button class="mode-card" data-action="review-mistakes" ${mistakes().length?'':'disabled'}><span class="pill">${mistakes().length} questions</span><h2>Review recent mistakes</h2><p>Revisit questions you last answered incorrectly. A correct checked answer removes that question from this list.</p><strong>Review with explanations →</strong></button>${Object.entries(subjects).map(([s,v])=>`<button class="mode-card" data-action="start-subject" data-subject="${s}"><span class="pill">${s} · 20 selected questions</span><h2>${v.name}</h2><p>${v.brief}. This round draws a random selection from the ${questions.filter(q=>q.subject===s).length}-question bank.</p><strong>Start subject practice →</strong></button>`).join('')}<button class="mode-card" data-action="start-all"><span class="pill">${questions.length} questions · no timer</span><h2>Complete question bank</h2><p>Work through every question. Your session and checked answers stay in this browser.</p><strong>Open the full bank →</strong></button></div><div class="notice" style="margin-top:24px">${badge()}<p>The MCQs and their explanations are newly authored revision aids. Each question links to its lesson and source basis. They are not claimed to be college past-paper questions.</p></div>${footer()}`}
  function startQuiz(pool,title,timed=false){saved.quiz={title,ids:pool.map(q=>q.id),index:0,responses:{},timed,deadline:timed?Date.now()+30*60*1000:null,finished:false,open:true};store();go('practice')}
  function record(qid,choice){saved.history[qid]={choice,correct:choice===questionById[qid].answer,at:Date.now()}}
  function finishQuiz(){const z=saved.quiz;if(!z||z.finished)return;z.finished=true;z.open=true;for(const [id,r] of Object.entries(z.responses)){r.checked=true;record(id,r.choice)}store();if(route().page==='practice')render()}
  function timeText(){const z=saved.quiz;const seconds=Math.max(0,Math.ceil((z.deadline-Date.now())/1000));return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`}
  function quizPage(){const z=saved.quiz;if(!z.ids?.length||z.ids.some(id=>!questionById[id])){saved.quiz=null;store();return practiceModes()}const q=questionById[z.ids[z.index]],a=z.responses[q.id],revealed=z.finished||(!z.timed&&a?.checked);const answered=Object.keys(z.responses).length;return `<div class="quiz-wrap"><button class="btn" data-action="exit-quiz">← Practice modes</button><div class="quiz-head"><div><span class="kicker">${z.timed?'Timed screening practice':'Practice with explanations'}</span><h1>${esc(z.title)}</h1><p class="muted">Question ${z.index+1} of ${z.ids.length} · ${answered} selected</p></div>${z.timed?`<div class="quiz-clock" id="clock" role="timer" aria-label="Time remaining">${z.finished?'Submitted':timeText()}</div>`:'<span class="pill">No timer</span>'}</div><div class="quiz-progress"><span style="width:${(z.index+1)/z.ids.length*100}%"></span></div>${z.finished?resultHtml(z):''}<section class="panel"><div class="question-top"><span class="pill">${q.subject} · ${esc(q.id)}</span>${badge()}</div><pre class="question-prompt">${esc(q.prompt)}</pre><div class="options">${q.options.map((v,i)=>`<button class="option ${a?.choice===i?'selected':''} ${revealed&&i===q.answer?'correct':''} ${revealed&&a?.choice===i&&i!==q.answer?'incorrect':''}" data-action="answer" data-choice="${i}" ${revealed?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span>${esc(v)}</span></button>`).join('')}</div>${revealed?`<div class="feedback"><b>${a?(a.choice===q.answer?'Correct.':'Review the reason.'):'No answer selected.'}</b><p><strong>Correct answer: ${esc(q.options[q.answer])}</strong></p><p>${esc(q.explanation)}</p>${link(`learn/${q.lesson}`,'Open the related visual lesson →')}</div>`:z.timed?'<p class="muted" style="font-size:12px">You can change selections before submission. Explanations appear after submission.</p>':`<div class="actions" style="margin-top:20px"><button class="btn primary" data-action="check-answer" ${a?'':'disabled'}>Check answer</button></div>`}</section><div class="quiz-nav"><button class="btn" data-action="quiz-prev" ${z.index===0?'disabled':''}>← Previous</button><span class="quiz-status">${revealed?'Explanation visible':'Choose an answer'}</span><button class="btn primary" data-action="quiz-next" ${z.index===z.ids.length-1?'disabled':''}>Next →</button></div><div class="quiz-jump"><label for="quiz-jump">Jump to a question</label><select id="quiz-jump">${z.ids.map((id,i)=>`<option value="${i}" ${i===z.index?'selected':''}>${i+1} · ${questionById[id].subject}${z.responses[id]?' · selected':''}</option>`).join('')}</select>${!z.finished?`<button class="btn" data-action="submit-quiz">${z.timed?'Submit mock':'Finish session'}</button>`:''}<button class="btn" data-action="restart-quiz">Restart this set</button></div></div>`}
  function resultHtml(z){const correct=z.ids.filter(id=>z.responses[id]?.choice===questionById[id].answer).length;const unanswered=z.ids.filter(id=>!z.responses[id]).length;return `<section class="quiz-result"><span class="kicker">Session result</span><p><strong>${correct} / ${z.ids.length}</strong> correct · ${unanswered} unanswered</p><p>Use the question selector below to inspect every answer and explanation. The result is practice feedback, not a prediction of your test score.</p><div class="summary-grid">${Object.keys(subjects).map(s=>{const qs=z.ids.filter(id=>questionById[id].subject===s);return qs.length?`<div class="review-row"><span>${s}</span><b>${qs.filter(id=>z.responses[id]?.choice===questionById[id].answer).length} / ${qs.length}</b></div>`:''}).join('')}</div></section>`}
  function sourcesPage(id){const s=sourceById[id];return `<div class="page-intro"><span class="kicker">Source library</span><h1>Keep the evidence visible.</h1><p>${sources.length} college sources and class examples. The PDFs include selected syllabus pages. Word text retains broader context; use the lesson links for the test scope.</p></div><div class="source-layout"><aside class="panel source-list"><label class="sr" for="source-search">Search sources</label><input type="search" id="source-search" placeholder="Search title, scope or text…"><div class="source-items" id="source-items">${sourceItems('',id)}</div></aside><article class="panel">${s?`<div class="source-heading"><span class="pill">${s.subject} · Original source</span><h2>${esc(s.name)}</h2><p>${esc(s.scope)}</p><p>The text below is an extraction. Images, layout and equations can be incomplete; open the original to check them. Original wording is preserved and can contain mistakes.</p><div class="actions"><a class="btn primary" href="${materialUrl(s)}" target="_blank" rel="noopener">Open original file ↗</a></div><p><b>Repository path:</b> ${esc(s.path)}</p><details><summary>Source fingerprint</summary><code>SHA-256: ${s.sha256}</code></details></div><pre class="source-text">${esc(s.text)}</pre>`:'<div class="empty"><h2>Select a source</h2><p>Read the extracted text or open the original file. Official supplemental references are listed on the coverage page.</p></div>'}</article></div>${footer()}`}
  function materialUrl(s){return location.protocol==='file:'?`../../../${s.path.split('/').map(encodeURIComponent).join('/')}`:`/materials/${encodeURIComponent(s.id)}`}
  function sourceItems(needle,id){needle=needle.toLowerCase();return sources.filter(s=>`${s.name} ${s.scope} ${s.text}`.toLowerCase().includes(needle)).map(s=>link(`sources/${s.id}`,`<b>${esc(s.name)}</b><small>${s.subject} · ${esc(s.scope)}</small>`,`source-item ${s.id===id?'active':''}`)).join('')||'<p class="muted">No source matches.</p>'}
  function termsPage(){return `<div class="page-intro"><span class="kicker">Terms in plain words</span><h1>Name the idea. See an example.</h1><p>${glossary.length} recurring terms with a concrete interpretation. ${badge()}</p></div><label class="sr" for="term-search">Search terms</label><div class="filters" style="grid-template-columns:1fr"><input type="search" id="term-search" placeholder="Search term, definition or example…"></div><dl class="term-grid" id="term-results">${termCards('')}</dl>${footer()}`}
  function termCards(needle){needle=needle.toLowerCase();return glossary.filter(t=>`${t.term} ${t.definition} ${t.example}`.toLowerCase().includes(needle)).map(t=>`<div class="panel"><dt>${esc(t.term)}</dt><dd>${esc(t.definition)}</dd><dd class="term-example">${esc(t.example)}</dd></div>`).join('')||'<div class="empty">No matching term.</div>'}
  function coveragePage(){return `<div class="page-intro"><span class="kicker">Coverage & provenance</span><h1>Know what is sourced.</h1><p>The screening notice determines the lesson scope. The college files provide a basis, and marked supplements fill the identified gaps.</p></div><div class="notice">${badge()}<p>This exact label appears on newly written teaching content. It does not claim that every college topic is missing. Each lesson separately states whether the topic is available, partial, or supplemented. Diagrams and questions are authored aids rather than copied college questions.</p></div><div class="stats"><div class="stat"><strong>${lessons.filter(l=>l.basis==='college').length}</strong><span>Topics with a college basis</span></div><div class="stat"><strong>${lessons.filter(l=>l.basis==='partial').length}</strong><span>Topics with partial coverage</span></div><div class="stat"><strong>${lessons.filter(l=>l.basis==='gap').length}</strong><span>Topics needing supplements</span></div><div class="stat"><strong>${sources.length}</strong><span>Preserved source entries</span></div></div><div class="coverage-grid">${Object.entries(subjects).map(([s,v])=>`<section class="panel"><span class="pill">${s}</span><h2>${v.name}</h2><p class="muted">${v.brief}</p><ul>${lessons.filter(l=>l.subject===s).map(l=>`<li>${link(`learn/${l.id}`,esc(l.title))} — ${basisText(l)}</li>`).join('')}</ul></section>`).join('')}</div><section class="panel" style="margin-top:24px"><span class="kicker">Read corrections with the source</span><h2>Important precision notes</h2><ul class="muted" style="line-height:1.9"><li>Waterfall describes a phase structure; it does not make earlier work physically impossible to revise.</li><li>A Git branch is a commit reference, not a mandatory physical project copy. Collaboration can still have conflicts.</li><li>The Scrum Guide allows Sprints of one month or less. Two-to-four weeks is a common example, not the full rule.</li><li>Signal, line-code and capacity material fills a CN gap. Its exact emphasis in your test is unknown.</li><li>Ordinary Hamming and extended SECDED codes have different guarantees. Full-duplex Ethernet does not use ordinary CSMA/CD collision handling.</li><li>TensorFlow code is explanatory Python. It is not executed by this browser site.</li></ul><h3>Official supplemental references</h3><div class="refs-list">${Object.values(official).map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(n)} ↗</a>`).join('')}<a href="https://www.asd-ste100.org/about_STE.html" target="_blank" rel="noopener">ASD-STE100 writing approach ↗</a></div></section>${footer()}`}
  function bindPage(r){
    if(r.page==='learn'&&!r.id){const subject=document.getElementById('lesson-subject');subject.value=filters.subject;for(const [id,key,event] of [['lesson-search','search','input'],['lesson-subject','subject','change'],['lesson-basis','basis','change'],['lesson-status','status','change']])document.getElementById(id).addEventListener(event,e=>{filters[key]=e.target.value;document.getElementById('lesson-results').innerHTML=lessonCards()})}
    if(r.page==='learn'&&r.id&&lessonTab==='visual')loadDiagram(r.id);else diagramToken++;
    document.getElementById('term-search')?.addEventListener('input',e=>document.getElementById('term-results').innerHTML=termCards(e.target.value));
    document.getElementById('source-search')?.addEventListener('input',e=>document.getElementById('source-items').innerHTML=sourceItems(e.target.value,r.id));
    document.getElementById('quiz-jump')?.addEventListener('change',e=>{saved.quiz.index=Number(e.target.value);store();render()});
  }
  root.addEventListener('change',e=>{if(e.target.id==='network-protocol'||e.target.id==='network-lost'){if(e.target.id==='network-protocol')lab.network=e.target.value;else lab.lost=Number(e.target.value);document.getElementById('lab').innerHTML=labHtml('CN')}});
  root.addEventListener('input',e=>{const key=e.target.dataset.parameter;if(key){lab[key]=Number(e.target.value);document.getElementById(`value-${key}`).textContent=lab[key].toFixed(1);document.getElementById('neuron-result').innerHTML=neuronResult(2*lab.w1+3*lab.w2+lab.bias)}});
  root.addEventListener('click',e=>{
    const button=e.target.closest('[data-action]');if(!button||button.disabled)return;
    const {action,id,subject,tab,step,choice}=button.dataset;
    if(action==='menu'){mobileOpen=!mobileOpen;document.querySelector('.sidebar').classList.toggle('open',mobileOpen);document.querySelector('.mobile-overlay').classList.toggle('open',mobileOpen);return}
    if(action==='theme'){saved.theme=saved.theme==='dark'?'light':'dark';store();document.body.classList.toggle('dark',saved.theme==='dark');button.textContent=saved.theme==='dark'?'☀ Light':'◐ Dark';return}
    if(action==='studied'){saved.studied=saved.studied.includes(id)?saved.studied.filter(x=>x!==id):[...saved.studied,id];store();render();return}
    if(action==='tab'){lessonTab=tab;render();document.getElementById(`tab-${tab}`)?.focus();return}
    if(action==='trace-step'){updateTrace(Number(step));return}
    if(action==='trace-prev'||action==='trace-next'){updateTrace(traceStep+(action==='trace-prev'?-1:1));return}
    if(action==='open-diagram'){openDiagram(id);return}
    if(action==='git-step'){lab.gitStep=Number(step);document.getElementById('lab').innerHTML=labHtml('SE');return}
    if(action==='dom-click'||action==='dom-reset'){lab.clicks=action==='dom-reset'?0:lab.clicks+1;document.getElementById('dom-count').textContent=lab.clicks;return}
    if(action==='start-subject'){startQuiz(shuffle(questions.filter(q=>q.subject===subject)).slice(0,20),`${subject} practice`);return}
    if(action==='start-mixed'){const pool=Object.entries({SE:8,WT:8,CN:7,AI:7}).flatMap(([s,n])=>shuffle(questions.filter(q=>q.subject===s)).slice(0,n));startQuiz(shuffle(pool),'Mixed screening mock',true);return}
    if(action==='start-all'){startQuiz(questions,'Complete bank');return}
    if(action==='review-mistakes'){startQuiz(shuffle(mistakes()),'Recent mistakes');return}
    if(action==='start-lesson'){startQuiz(questions.filter(q=>q.lesson===id),lessonById[id].title);return}
    if(action==='start-question'){startQuiz([questionById[id]],'Explain this question');return}
    if(action==='resume'){saved.quiz.open=true;if(saved.quiz.timed&&!saved.quiz.finished&&Date.now()>=saved.quiz.deadline)finishQuiz();store();render();return}
    if(action==='exit-quiz'){saved.quiz.open=false;store();render();return}
    const z=saved.quiz;if(!z)return;
    if(action==='answer'){const qid=z.ids[z.index];z.responses[qid]={choice:Number(choice),checked:false};store();render();return}
    if(action==='check-answer'){const qid=z.ids[z.index];if(z.responses[qid]){z.responses[qid].checked=true;record(qid,z.responses[qid].choice);store();render()}return}
    if(action==='quiz-prev'||action==='quiz-next'){z.index=Math.max(0,Math.min(z.ids.length-1,z.index+(action==='quiz-prev'?-1:1)));store();render();return}
    if(action==='submit-quiz'){finishQuiz();return}
    if(action==='restart-quiz'){startQuiz(z.ids.map(id=>questionById[id]),z.title,z.timed);return}
  });
  root.addEventListener('keydown',e=>{if(e.target.getAttribute('role')==='tab'&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=['visual','read','compare'];let n=tabs.indexOf(lessonTab);n=e.key==='Home'?0:e.key==='End'?2:(n+(e.key==='ArrowRight'?1:2))%3;lessonTab=tabs[n];render();document.getElementById(`tab-${lessonTab}`).focus()}});
  addEventListener('hashchange',()=>{mobileOpen=false;render();window.scrollTo(0,0)});
  setInterval(()=>{const z=saved.quiz;if(!z?.timed||z.finished)return;if(Date.now()>=z.deadline){finishQuiz();return}const clock=document.getElementById('clock');if(clock){clock.textContent=timeText();clock.classList.toggle('timer-warn',z.deadline-Date.now()<60000)}},1000);
  if(saved.quiz?.timed&&!saved.quiz.finished&&Date.now()>=saved.quiz.deadline)finishQuiz();
  render();
})();
